# The lookback window prior to visit date for each feature category. Records taken within this time window are valid.
trt_lookback_window: [-28, 0] # days
lab_lookback_window: [-5, 0] # days
symp_lookback_window: [-30, 0] # days
ed_visit_lookback_window: 5 # years

# a2r deployment config
trt_lookahead_window_deployment: 5 # days
lab_lookback_window_deployment: [-7, -1] # days
symp_lookback_window_deployment: [-30, -1] # days
ed_visit_lookback_window_deployment: 5 # years
