# This workflow will run the tests for the make-clinical-dataset package
name: Test make-clinical-dataset package

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.11
    - run: |
        pip install -r requirements.txt
        pip install pytest pytest-xdist
        pytest -n 2