# This workflow will run the tests for the make-clinical-dataset package
name: Test make-clinical-dataset package

on:
  push:
    branches: [ main ]

  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install -e .
        # pip install tqdm pandas pyarrow pyyaml pytest pytest-xdist

    - name: Run test
      run: pytest -n 2